name: Build and Release JARs

on:
  workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Download and install mpc4j
      run: |
        wget https://github.com/alibaba-edu/mpc4j/archive/refs/tags/v1.1.1.tar.gz
        tar -xzf v1.1.1.tar.gz
        cd mpc4j-1.1.1
        mvn install

    - name: Build atdkg project
      run: |
        cd atdkg
        mvn clean package

    - name: Run computation test
      run: |
        cd atdkg/target
        java -jar computationtest.jar 9 15 2>&1 | tee computation_test.log

    - name: Upload test log
      uses: actions/upload-artifact@v4
      with:
        name: computation-test-log
        path: atdkg/target/computation_test.log
